version: "3.9"
networks:
    etl-network:
services:
    etl:
        build:
            context: .
            dockerfile: maven.Dockerfile
        depends_on:
            - sql
            - my-sql
        networks:
            - etl-network
        volumes:
            - "./dataRefresh:/app/dataRefresh"
        command: sleep 10000
    sql:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "Temporal+123"
            ACCEPT_EULA: "Y"
        ports: 
            - 1433:1433
        networks:
            - etl-network
    my-sql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Temporal+123
        ports: 
            - 3306:3306
            - 33060:33060
        networks:
            - etl-network