version: "3.9"
networks:
    etl-network:
services:
    etl:
        container_name: etl
        build:
            context: .
            dockerfile: maven.Dockerfile
        networks:
            - etl-network
        volumes:
            - "./dataRefresh:/app/dataRefresh"
